language: r

sudo: true

r:
  - release

os:
  - linux
  - osx

script:
  Rscript -e 'rmarkdown::render("slides/15-linear_model/linear_model.Rmd")'
  Rscript -e 'rmarkdown::render("slides/16-logistic_regression/logistic_regression.Rmd")'

cache:
  packages: yes

r_packages:
  - rmarkdown
  - neotoma
  - purrr
  - plyr
  - reshape2
  - mgcv
  - Bchron
  - viridis
  - dplyr
  - readr
  - gridExtra
  - faraway
  - tidyverse
  - gtsummary
  - MASS
  - splines
  - caret
  - glmnet
  - pROC
#http://www.goring.org/resources/Adding_CI_To_RMarkdown.html