language: r

r:
  - release

os:
  - linux
  - osx

script:
  make linear_model
  make clean

cache:
  packages: yes

r_packages:
  - rmarkdown
  - neotoma
  - purrr
  - plyr
  - reshape2
  - mgcv
  - Bchron
  - viridis
  - dplyr
  - readr
  - gridExtra
  - faraway
  - tidyverse
  - gtsummary
  - MASS
  - splines
#http://www.goring.org/resources/Adding_CI_To_RMarkdown.html